### ISSUE TITLE
Deshabilitar funciones en Admin

### ISSUE THREAD

**Issue by dukenicols** [dukenicols/Linkpro#4]
Se esta bloqueando otro plugin
Con Linkpro:
![unnamed 1](https://cloud.githubusercontent.com/assets/5882461/9484409/0f1c03ea-4b82-11e5-98ba-8d3bb9e2644d.jpg)
Sin Linkpro:
![unnamed 2](https://cloud.githubusercontent.com/assets/5882461/9484410/106f120a-4b82-11e5-953c-1e2082c2bd99.jpg)

**Comment by ezequielcosentino** [comment]
SI DESACTIVO EL LINKPRO

ERROR DE LOGIN: SI (IGUAL) 
ERROR DE VINCULACION: NO (SOLUCION CON DESACTIVAR EL LINKPRO). SI ACTIVO LINKPRO NO PUEDO NI ACCEDER A EDITAR LA PAGINA EN VIVO, PORQUE ME LLEVA A CAMBIAR PASS.
CAMBIO DE CONTRASEÑA: SI (IGUAL)
PROBLEMA DE ONLINE/OFFLINE ADMINISTRADORES: NO (SOLUCION CON DESACTIVAR EL LINKPRO).

**Comment by ezequielcosentino** [comment]
VOY A RECLAMAR AL PROGRAMADOR:

- ERROR DE LOGIN + (VER SI ES EL FORMULARIO O SHOTCODE QUE TIENE EL REDIRECT.
- CAMBIO DE CONTRASEÑA

**Comment by dukenicols** [comment]
@ezequielcosentino voy a solucionar el error de vinculacion, agregare un parametro en la url que permita salir del proceso normal.

**Comment by dukenicols** [comment]
@ezequielcosentino explicame un poco el:

> problema de online/offline administradores

**Comment by ezequielcosentino** [comment]
Imagen de correo numero 4.
En las funciones del plugin, Ajustes de Modulo, indica si habilita o no el icono de Online/offline en los usuarios que son administradores.
